import os
import time
#author : mr awerty
os.system("clear")
time.sleep(3)
print("")
print("loading...")
print("----------------------------loading-----------------------------")
time.sleep(2)
print("[-1%-]")
time.sleep(3)
print("[-9%-]")
time.sleep(1)
print("[-37%-]")
time.sleep(1)
print("[-78%-]")
time.sleep(2)
print("[-93%-]")
time.sleep(1)
print("[-100%-]")
print("")
os.system("clear")
time.sleep(2)
print(" _______           _______  _______ _________                  _________")
print("(  ___  )|\     /|(  ____ \(  ____ )\__   __/|\     /||\     /|\__   __/")
print("| (   ) || )   ( || (    \/| (    )|   ) (   ( \   / )| )   ( |   ) (")
print("| (___) || | _ | || (__    | (____)|   | |    \ (_) / | |   | |   | |")
print("|  ___  || |( )| ||  __)   |     __)   | |     \   /  | |   | |   | |")
print("| (   ) || || || || (      | (\ (      | |      ) (   | |   | |   | |")
print("| )   ( || () () || (____/\| ) \ \__   | |      | |   | (___) |___) (___")
print("|/     \|(_______)(_______/|/   \__/   )_(      \_/   (_______)\_______/")
print("                             version == > 1.0")
print("                     [<author ==> mr awerty / shermond>]")
print("")
print("silahkan pilih tools yang telah di sediakan => :")
print("")
print("1.awal mula tentang awertyui ini dibuat")
print("")
print("2.tentang")
print("")
input = input("input anda => ")

if input == "1":
 time.sleep(2)
 os.system("clear")
 os.system("figlet awal mula awertyui")
 print("")
 print("awal mula awertyui si buat, jadi awal nya disebabkan oleh kegabutan dan ke jeniusan si mr awerty/saya dan saya membuat tools ini karena terinspirasi oleh teman saya mii dan tools ddos.")
 print("")
time.sleep(2)
os.system("exit")

if input == "2":
 time.sleep(2)
 os.system("clear")
 os.system("figlet about")
 print("")
 print("developer : mr awerty/shermond")
 print("")
 print("no wa owner/dev : 6285141705599")
 print("")
 print("nama organisasi : C.G.H.H.A (cyber gray hat hacker attacker) ")
 print("")
 print("note: kemungkinan owner/dev ganti no wa kalo tidak bisa dihubungi berarti owner lagi gk ad kuota ato wifi tapi kalo sudah berminggu minggu berarti owner/dev telah ganti nomor")
 print("")
time.sleep(2)
os.system("exit")
